name: Website Deploy
on:
  push:
    branches:
      - main
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: GCP Authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Debug Service Account (safe)
        run: |
          SA_EMAIL=$(jq -r '.client_email' "$GOOGLE_APPLICATION_CREDENTIALS")
          PROJECT_ID=${{ secrets.GCP_PROJECT }}

          echo "Service Account: $SA_EMAIL"

          gcloud projects get-iam-policy "$PROJECT_ID" \
            --flatten="bindings[].members" \
            --filter="bindings.members:serviceAccount:$SA_EMAIL" \
            --format="table(bindings.role)"

      - name: Docker Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/website-amadomaker/image-website:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: GCP Authentication
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Deploy to Cloud Run
        id: deploy-cloudrun
        uses: google-github-actions/deploy-cloudrun@v3
        with:
          service: website-amadomaker
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/website-amadomaker/image-website:${{ github.sha }}
      - name: Use Output URL
        run: echo "Deployed to ${{ steps.deploy-cloudrun.outputs.url }}"